import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Login from '../Layout/Login'
// import { createContext } from 'react'
// export const UserContext = createContext();
import { useState } from 'react'
import TodoList from '../Components/TodoList'

export default function Home() {
  return ( 
    <div>
      <Head>
        <title>To DO APPLICATION</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Login/>
      </main>
    </div>
  )
}
